version: "3.8"

services:
  sslly-nginx:
    build: .
    container_name: sslly-nginx
    network_mode: host
    restart: on-failure
    volumes:
      - ./configs:/app/configs:ro
      - ./ssl:/app/ssl:ro
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
      - LANGUAGE=zh_CN:zh
      - LC_ALL=zh_CN.UTF-8
